apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kbtvuelo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Geckomonc/Laboratorio3'
    targetRevision: HEAD
    path: .  # Raíz del repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
